version = 1

test_patterns = ["*.py"]

exclude_patterns = [
    "*.c",
    "*.o",
    "*.so"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"